apiVersion: v1
kind: Secret
metadata:
  name: final-secret
  namespace: spoke-logging-creds
  annotations:
    ran.openshift.io/ztp-deploy-wave: "6"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""