apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: $networkName
  namespace: openshift-sriov-network-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
spec:
  networkNamespace: openshift-sriov-network-operator
#  resourceName: ""
#  vlan: ""
#  spoofChk: ""
#  ipam: ""
#  linkState: ""
#  maxTxRate: ""
#  minTxRate: ""
#  vlanQoS: ""
#  trust: ""
#  capabilities: ""
