---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "custom-4.14"
  namespace: "ztp-clusters"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    common: "true"
    du-profile: "4.14"
  sourceFiles:
    # Create operators policies that will be installed in all clusters
    #- fileName: custom-crs/kubeapiserver-debug.yaml
    #  remediationAction: inform
    #  policyName: "custom-4.14-kubeapi-debug-policy"
    - fileName: Nmstate.yaml
      policyName: "config-policy"