
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno166-config"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "sno166"
    version: OCP
  sourceFiles:
    - fileName: custom/LabelNode.yaml
      policyName: config
      metadata:
        name: sno166.workload.bos2.lab
        labels:
          node-role.kubernetes.io/standard: ""
    - fileName: custom/CustomSecret.yaml
      policyName: "local-secret-copy"
      spec: 
        apiVersion: v1
        kind: Secret
        metadata:
          name: final-secret
          namespace: spoke-logging-creds
        type: Opaque
        data:
          # Adding | autoindent ensures the string aligns if it's long
          AWS_ACCESS_KEY_ID: '{{ (fromSecret "spoke-storage-creds" "loki-bucket-odf" "AWS_ACCESS_KEY_ID") | default "" | autoindent }}'
          AWS_SECRET_ACCESS_KEY: '{{ (fromSecret "spoke-storage-creds" "loki-bucket-odf" "AWS_SECRET_ACCESS_KEY") | default "" | autoindent }}'