---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group-zones-configmap
  namespace: ztp-group
data:
  # ClusterLogForwarder.yaml
  zone-1-cluster-log-fwd-filters-labels: '{"label1": "test1", "label2": "test2"}'
  zone-1-cluster-log-fwd-outputs-urls: 'tcp://10.46.55.190:9092/test'
  # StoragePVC.yaml
  zone-1-storagepvc-storage: "100Gi"
