apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    ran.openshift.io/ztp-deploy-wave: "1"
data:
  config.yaml: |
    enableUserWorkload: true
    alertmanagerMain:
      enabled: true
    telemeterClient:
      enabled: false
    prometheusK8s:
       retention: 24h
