# example-node[123]-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-3node
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "compactcluster-hpe"
  namespace: "compactcluster-hpe"
spec:
  baseDomain: "workload.bos2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-compactcluster-hpe"
  clusterImageSetNameRef: "img4.19.7-x86-64-appsub"

  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyhoIabaCD8Tx7W6ZVvaXGfaw3ZHkLSwgV0TS9d6l6B6PY9CQTd/7PXqWvzp8xqQX+NXDMmMZahUu95cxZ2JJBKgqQV8JTajY1LK8hIjBoxFw4CL1aEHe3Vvf26GjD29D7G0SMxvbgbbQlUYZ82cpNc/QDvnA36PVo6LCkJH0yfcdPzQyj8zXPpO28Kxf17yg6O4LJz/jmRLXIiP2UUmyfl/CCfI2vJ/TuSX5PD7gCn6Ccr8ewtyoaKQ8n8XUPAE7roYDbFJ9C6j4sMPcMUJ44O1Mx4gUwJl+lQ+iLNnZSvRaq9Iu91qbMxQo1/vtUjPW/dKNwGh20VzJZ2cKhpzFpL4brfkr3y/ywmeQVUaIuX3FwoKe4cpH3CoVID6lr8uz1fObNulTP0wZItSJbImVuwWf95qnHSJc5r2ClbMn1JATy/dP19OQxTLw1NSrd7x944Edud+yv42LV111zHYuckIlGEkuiwUbLlvodZXohj3LjQoK/XS12zLrdhY+ymPc= kni@ocp414-prov"
  clusters:
  - clusterName: "compactcluster-hpe"
    extraManifests:
        searchPaths:
          - extra-manifest/
    #      - custom-manifests/
    #    filter:
    #      inclusionDefault: include
    #      exclude:
    #        - 76-enable-crun-master.yaml
    #        - 77-enable-crun-standard.yaml
    #        - 78-enable-crun-ht100gb.yaml
    #        - 80-kubeapiserver-debug.yaml
    networkType: "OVNKubernetes"
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.compactextra-manifest.
    # extraManifestPath: compactextra-manifest
    # - NodeTuning is needed for 4.13 and later, not for 4.12 and earlier
    # installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    clusterLabels:
        common: true
        sites: "mno"
        group: "mno"
        version: "OCP"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.18.0/25
    serviceNetwork:
      - 172.30.0.0/16
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    apiVIP: 192.168.18.101
    ingressVIP: 192.168.18.102
    additionalNTPSources:
      - pool.ntp.org
      - clock.corp.redhat.com
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    # cpuPartitioningMode: None
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
    nodes:
      - hostName: "master-node1.workload.bos2.lab"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.18.180/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "master-node1-bmc-secret"
        bootMACAddress: "b4:96:91:c6:59:b4"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sdb
        nodeNetwork:
          interfaces:
            - name: "ens1f0"
              macAddress: "b4:96:91:c6:59:b4"
          config:
            interfaces:
              - name: "ens1f0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.18.102
                    prefix-length: 25
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1f0
                next-hop-address: 192.168.18.1
                table-id: 254
      - hostName: "master-node2.workload.bos2.lab"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.18.183/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "master-node2-bmc-secret"
        bootMACAddress: "b4:96:91:b7:2e:1c"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/disk/by-path/pci-0000:00:00.5-pci-10000:82:00.0-nvme-1
        nodeNetwork:
          interfaces:
            - name: "ens1f0"
              macAddress: "b4:96:91:b7:2e:1c"
          config:
            interfaces:
              - name: "ens1f0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  - ip: 192.168.18.103
                    prefix-length: 25
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1f0
                next-hop-address: 192.168.18.1
                table-id: 254
      - hostName: "master-node3.workload.bos2.lab"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://192.168.18.184/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "master-node3-bmc-secret"
        bootMACAddress: "50:7C:6F:53:E8:A4"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sdb
        nodeNetwork:
          interfaces:
            - name: "ens1f0"
              macAddress: "50:7C:6F:53:E8:A4"
          config:
            interfaces:
              - name: "ens1f0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  - ip: 192.168.18.104
                    prefix-length: 25
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1f0
                next-hop-address: 192.168.18.1
                table-id: 254