# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno186"
  namespace: "sno186"
spec:
  baseDomain: "workload.bos2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-sno186"
  clusterImageSetNameRef: "img4.20.3-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyhoIabaCD8Tx7W6ZVvaXGfaw3ZHkLSwgV0TS9d6l6B6PY9CQTd/7PXqWvzp8xqQX+NXDMmMZahUu95cxZ2JJBKgqQV8JTajY1LK8hIjBoxFw4CL1aEHe3Vvf26GjD29D7G0SMxvbgbbQlUYZ82cpNc/QDvnA36PVo6LCkJH0yfcdPzQyj8zXPpO28Kxf17yg6O4LJz/jmRLXIiP2UUmyfl/CCfI2vJ/TuSX5PD7gCn6Ccr8ewtyoaKQ8n8XUPAE7roYDbFJ9C6j4sMPcMUJ44O1Mx4gUwJl+lQ+iLNnZSvRaq9Iu91qbMxQo1/vtUjPW/dKNwGh20VzJZ2cKhpzFpL4brfkr3y/ywmeQVUaIuX3FwoKe4cpH3CoVID6lr8uz1fObNulTP0wZItSJbImVuwWf95qnHSJc5r2ClbMn1JATy/dP19OQxTLw1NSrd7x944Edud+yv42LV111zHYuckIlGEkuiwUbLlvodZXohj3LjQoK/XS12zLrdhY+ymPc= kni@ocp414-prov"
  clusters:
  - clusterName: "sno186"
    extraManifests:
        searchPaths:
          - extra-manifest/
          - custom-manifests/
        filter:
          inclusionDefault: include
          exclude:
            - 76-enable-crun-master.yaml
            - 77-enable-crun-standard.yaml
            - 78-enable-crun-ht100gb.yaml
    #        - 80-kubeapiserver-debug.yaml
    installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"OperatorLifecycleManager\", \"marketplace\", \"Console\", \"Ingress\", \"NodeTuning\" ] }}"
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.sno-extra-manifest.
    # extraManifestPath: sno-extra-manifest
    networkType: "OVNKubernetes"
    #installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"OperatorLifecycleManager\", \"marketplace\", \"Console\", \"Ingress\", \"NodeTuning\" ] }}"
    clusterLabels:
        common: true
        sites: "sno186"
        group: "sno"
        version: "OCP"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.18.0/25
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - pool.ntp.org
      - clock.corp.redhat.com
    # Initiates the cluster for workload partitioning. Setting specific reserved/isolated CPUSets is done via PolicyTemplate
    # please see Workload Partitioning Feature for a complete guide.
    cpuPartitioningMode: None
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "sno186.workload.bos2.lab"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://192.168.18.186/redfish/v1/Systems/1"
        bmcCredentialsName:
          name: "sno186-bmc-secret"
        bootMACAddress: "b8:3f:d2:7e:af:6e"
        # cpuset: "0,2,30,32,34,36,62,64"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/disk/by-path/pci-0000:02:00.0-nvme-1
        # example of diskPartition below is used for image registry (check ImageRegistry.md for more details), but it's not limited to this use case
#        diskPartition:
#          - device: /dev/disk/by-id/wwn-0x11111000000asd123 # match rootDeviceHints
#            partitions:
#              - mount_point: /var/imageregistry
#                size: 102500
#                start: 344844
        nodeNetwork:
          interfaces:
            - name: "ens14f0np0"
              macAddress: "b8:3f:d2:7e:af:6e"
          config:
            interfaces:
              - name: "ens14f0np0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  - ip: 192.168.18.70
                    prefix-length: 25
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens14f0np0
                next-hop-address: 192.168.18.1
                table-id: 254
