# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno166"
  namespace: "sno166"
spec:
  baseDomain: "workload.bos2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret-sno166"
  clusterImageSetNameRef: "img4.20.8-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyhoIabaCD8Tx7W6ZVvaXGfaw3ZHkLSwgV0TS9d6l6B6PY9CQTd/7PXqWvzp8xqQX+NXDMmMZahUu95cxZ2JJBKgqQV8JTajY1LK8hIjBoxFw4CL1aEHe3Vvf26GjD29D7G0SMxvbgbbQlUYZ82cpNc/QDvnA36PVo6LCkJH0yfcdPzQyj8zXPpO28Kxf17yg6O4LJz/jmRLXIiP2UUmyfl/CCfI2vJ/TuSX5PD7gCn6Ccr8ewtyoaKQ8n8XUPAE7roYDbFJ9C6j4sMPcMUJ44O1Mx4gUwJl+lQ+iLNnZSvRaq9Iu91qbMxQo1/vtUjPW/dKNwGh20VzJZ2cKhpzFpL4brfkr3y/ywmeQVUaIuX3FwoKe4cpH3CoVID6lr8uz1fObNulTP0wZItSJbImVuwWf95qnHSJc5r2ClbMn1JATy/dP19OQxTLw1NSrd7x944Edud+yv42LV111zHYuckIlGEkuiwUbLlvodZXohj3LjQoK/XS12zLrdhY+ymPc= kni@ocp414-prov"
  clusters:
  - clusterName: "sno166"
    extraManifests:
        searchPaths:
          - extra-manifest/
          - custom-manifests/
        filter:
          inclusionDefault: include
          exclude:
            - 76-enable-crun-master.yaml
            - 77-enable-crun-standard.yaml
            - 78-enable-crun-ht100gb.yaml
            - 99-cgroupsv1.yaml
    networkType: "OVNKubernetes"
    #installConfigOverrides:  "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
    clusterLabels:
        common: true
        sites: "sno166"
        group: "sno"
        version: "OCP"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.18.0/25
    serviceNetwork:
      - 172.30.0.0/16
    additionalNTPSources:
      - pool.ntp.org
      - clock.corp.redhat.com
    cpuPartitioningMode: AllNodes
    nodes:
      - hostName: "sno166.workload.bos2.lab"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "idrac-virtualmedia://192.168.18.166/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "sno166-bmc-secret"
        bootMACAddress: "50:7c:6f:53:e8:34"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sdb
        nodeNetwork:
          interfaces:
            - name: "ens1f0"
              macAddress: "50:7c:6f:53:e8:34"
          config:
            interfaces:
              - name: "ens1f0"
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  - ip: 192.168.18.48
                    prefix-length: 25
            dns-resolver:
              config:
                search:
                - workload.bos2.lab
                server:
                - 192.168.18.9
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: ens1f0
                next-hop-address: 192.168.18.1
                table-id: 254
