---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-common
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-group
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-site
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-upgrade
